version: '3.1'
services:
  db:
    image: postgres
    container_name: posrgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=test_db
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    image: node
    dockerports:
      - 3001:3001
    volumes:
      - ./api/:/app
    command: npm start
